# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["ffmpeg-full", "python311", "libopus", "libsodium"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "cd discord-music-bot && python bot.py"
